travis:
  secure:
    BINSTAR_TOKEN: BGjke5WGoQZLWg9+m5e+RTCHbnOChs/Xq1WZgVdiYxBwkhzCOmB9C85NL2fJIULu4Y1PGkelgEp9FxfB3/5wtwlwzOBdBRivnKwtpwiIYsgy8MKCdXki3sNZl0DOBJ0mFlbdbEazlLzwnTmMpCT5uxDclEFO7naO2Xk1vEI7JUebwiA6Wc03SxM/hcj8kiWyPY8ZVm1xvVunGLQrbpN84yM3BKzTQ5v/iQHKkByflGCl5q2fk9otOvqa+bkKc0hAFS8Om2znriXFT8DoYnJ7y5yyDeSc+JDSTvOLS2qbi63eGs/OI2tRSe9hr3Eq+2Zzb5NHlLMnfxDvFyACahDcf5MCY7qq4HU/VQxjoIKSLnURTb4ZdpB1W6q4SxxuyoD3CpiGSltzYve5YMGJF4eLn4dVmyqqoXRNmgIHr/jIIYrONu61p2owvYBZ0iJNosbUYWAfe7AgcYor/TSLikC4w7d5zQ+49Ki6KrYOAMGblSCVyrXSNHNsBZUC1iAi8KdkJKsXtwtpTJHCfRKmTjC4T9h5BnU0M9m3C3gLev1+HlAWA+dUY1eYp44myPFs524iHGZ/KZ1axrIX25OBOROiHFAfWKC7g6nuI4/D3/3gq6t+DjJG/4JjG3IDFzQXcmEjhle8i//Rj9Ga+qjtksGXJ3dy/bPLcnLb0qHN+oOGgkU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
